import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(root, "SOUL.md");
const outputPath = resolve(root, "src/lib/coast/soul.generated.ts");
const source = await readFile(sourcePath, "utf8");
const hash = createHash("sha256").update(source, "utf8").digest("hex");
const generated = `/* This file is generated by scripts/generate-soul.ts. Do not edit it directly. */\nexport const COAST_SOUL_SOURCE_SHA256 = ${JSON.stringify(hash)} as const;\nexport const COAST_SOUL = ${JSON.stringify(source)} as const;\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    // The missing file is reported by the comparison below.
  }
  if (current !== generated) {
    console.error("COAST soul generated output is stale. Run pnpm soul:generate.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated, "utf8");
}
